name: deno

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno task test
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno fmt --check
      - run: deno lint
      - name: Run deno task check
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'

          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install fd

          deno task check

